### ISSUE TITLE
Cannot use Social Login

### ISSUE THREAD

**Issue by thirdknife** [galaxyproject/cloudlaunch#100]
I have setup locally. When I try to use social login to sign up I get Internal server error.

```
Environment:


Request Method: GET
Request URL: http://localhost:4200/accounts/google/login/

Django Version: 1.11.5
Python Version: 3.5.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'nested_admin',
 'smart_selects',
 'corsheaders',
 'rest_framework.authtoken',
 'rest_auth',
 'allauth',
 'allauth.account',
 'rest_auth.registration',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.facebook',
 'allauth.socialaccount.providers.github',
 'allauth.socialaccount.providers.google',
 'allauth.socialaccount.providers.twitter',
 'baselaunch',
 'rest_framework',
 'kombu.transport.django',
 'djcelery',
 'django_countries']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth2/views.py" in view
  73.                 return self.dispatch(request, *args, **kwargs)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth2/views.py" in dispatch
  96.         app = provider.get_app(self.request)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/allauth/socialaccount/providers/base.py" in get_app
  52.         return SocialApp.objects.get_current(self.id, request)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/allauth/socialaccount/models.py" in get_current
  40.                 provider=provider)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/Users/shakeel/Bioinformatics/biocentral/venv/lib/python3.5/site-packages/django/db/models/query.py" in get
  380.                 self.model._meta.object_name

Exception Type: DoesNotExist at /accounts/google/login/
Exception Value: SocialApp matching query does not exist.
```

What's missing for me?

**Comment by nuwang** [comment]
@thirdknife You'll need to go into the django admin at localhost:8000/admin and register a social application under "social accounts". We use django-allauth for social login, so configuration instructions for various platforms are available here: https://django-allauth.readthedocs.io/en/latest/

I usually use twitter or github since they are localhost friendly.

**Comment by machristie** [comment]
If it helps here are my notes on what I did to add GitHub locally:

----
Setting up allauth for GitHub
* for localhost development, change the domain of **example.com** in **Sites** in admin to `localhost`
* create a **social application** in admin
    * select GitHub as provider
    * client id and secret
        * come from creating a [Developer OAuth App in GitHub](https://github.com/settings/developers)
    * add the `localhost` site

**Comment by thirdknife** [comment]
All set up but getting this error.

<img width="1440" alt="screen shot 2017-10-13 at 11 23 32 pm" src="https://user-images.githubusercontent.com/885125/31560414-9d8c92c8-b06d-11e7-88f2-2f1ad0c6c313.png">

and application under Github looks like this.

<img width="812" alt="screen shot 2017-10-13 at 11 25 01 pm" src="https://user-images.githubusercontent.com/885125/31560568-3c4a673c-b06e-11e7-8bbc-7192996079a2.png">

**Comment by afgane** [comment]
It should be port 4200 instead of 8000, like so:
![image](https://user-images.githubusercontent.com/338642/31561803-131ddc32-b027-11e7-9ac7-504e5807c55c.png)

**Comment by thirdknife** [comment]
Did it, same thing. 4200 is the frontend, the callback should be with django?

**Comment by afgane** [comment]
The callback is going back to the frontend and hence the url/port must match. Sorry for reiterating but can you please check that the _Authorization callback URL_ is the one pointing to port 4200? I just tried swapping this around a bit and if I set it to 8000, I get the same error you captured above.

**Comment by thirdknife** [comment]
It worked! After accessing the Github grant I am shown this page.

<img width="1440" alt="screen shot 2017-10-14 at 12 32 22 am" src="https://user-images.githubusercontent.com/885125/31563147-5d5c1e62-b077-11e7-9694-bcf59b96d1bf.png">

**Comment by nuwang** [comment]
@thirdknife Does your django superuser name or e-mail happen to be the same as the github login? If so, you may be presented with this page. Try changing your superuser name/e-mail to be unique, and it should work.

**Comment by thirdknife** [comment]
Yeah, I registered with different email but my thought was about the styling. Is this styling expected?

**Comment by nuwang** [comment]
Yes, we haven't created a replacement template, since this issue would generally only crop up for developers.

**Comment by nuwang** [comment]
I guess we can close this issue, but would need to open two new ones
1. Add dev. instructions on configuring local dev auth setup.
2. Create replacement template for all-auth signup

**Comment by nuwang** [comment]
@thirdknife Thanks for reporting these. I've created two new issues above for further tracking. Let is know if you run into any more issues.
