### ISSUE TITLE
Add dev. instructions on configuring local dev auth setup

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/cloudlaunch#101]
Currently, there are no instructions on how to get started with a local cloudlaunch, and how to configure initial social auth settings etc. See: https://github.com/galaxyproject/cloudlaunch/issues/100 for context.

**Comment by afgane** [comment]
Should be done with e314026bd5a3d2f337d4902a7bf2c2e611507c2c, 1d1e8d983e5bb41286dd35f94bac6978f5b4aae8, and 5e73159cd017332da8271efe1cbacf83a7228cec
