### ISSUE TITLE
Launching appliance v16.10 and v17.05 appears to fail in web UI

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudlaunch#110]
### Steps to reproduce
Launch either version 16.10 or 17.05 using https://beta.launch.usegalaxy.org/catalog/appliance/galaxy-cloud

### Observed results
* Web UI shows "FAILURE" in the Status column
* Cluster launches successfully

### Expected results
Web UI to show correct cluster status

**Comment by afgane** [comment]
This was fixed in https://github.com/galaxyproject/cloudlaunch/commit/61ee978eb77b57160c933f090fa7350a6185d2b5. Thanks for the report.

**Comment by hackdna** [comment]
Great, thanks, it works for me now.
