### ISSUE TITLE
Impossible to retrieve saved clusters

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudlaunch#112]
### Steps to reproduce
1. Go to step 2 of [launching a Galaxy Cloudman appliance](https://beta.launch.usegalaxy.org/catalog/appliance/galaxy-cloud) 
1. Click on "Fetch Saved Clusters"

### Observed results
* "Retrieving Saved Clusters" is displayed but list of saved clusters never appears
* Web browser console shows:
```
GET https://beta.launch.usegalaxy.org/cloudlaunch/api/v1/infrastructure/clouds/amazon-us-east-n-virginia/cloudman/ 404 (Not Found)
XHR failed loading: GET "https://beta.launch.usegalaxy.org/cloudlaunch/api/v1/infrastructure/clouds/amazon-us-east-n-virginia/cloudman/".
```

### Expected results
Should be possible to select a saved cluster from a list

**Comment by nuwang** [comment]
Thanks for reporting this. This has been fixed in: https://github.com/galaxyproject/cloudlaunch/commit/6e414211a322c39440eccb3dc0069da300732683
We'll push it out to the server tomorrow when the server is less busy.

**Comment by nuwang** [comment]
The fix has been pushed out - let us know if it looks ok now.

**Comment by hackdna** [comment]
Thanks, now the list of saved clusters is displayed. However, there is now a message: "SyntaxError: Unexpected token < in JSON at position 0" between "Advanced CloudMan options" and the instance type dropdown which shows "Retrieving instance types..." and is not selectable.

**Comment by hackdna** [comment]
Closing in favor of #113
