### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by HEHgit** [galaxyproject/cloudlaunch#113]
Hi, 
I'm using CloudLaunch for galaxy cloudman. Recently, I get an issue which prevents me to choose the kind of AWS instance I want to use (cf Image below).
![image](https://user-images.githubusercontent.com/32955596/32221212-f3d65d6a-be34-11e7-8424-37dca94b0949.png)
It's the only thing which is not working, as I can't choose an instance type, I leave it blank and a galaxy instance on m4.4xlarge is launched.

Thank you in advance for your help

**Comment by hackdna** [comment]
See also: http://dev.list.galaxyproject.org/AWS-launch-error-tt4671159.html

**Comment by afgane** [comment]
@hackdna are you also seeing above issue? As I replied to that email, I'm not able to replicate this.

**Comment by hackdna** [comment]
Yes, on beta.launch.usegalaxy.org but not on launch.usegalaxy.org. I'm using Chrome 61 on OS X 10.12.6. Browser console shows:
```
/cloudlaunch/api/v1/infrastructure/clouds/amazon-us-east-n-virginia/compute/regions/us-east-1/zones/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/cloudlaunch/api/v1/infrastructure/clouds/amazon-us-east-n-virginia/compute/vm_types/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/cloudlaunch/api/v1/infrastructure/clouds/amazon-us-east-n-virginia/security/keypairs/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/cloudlaunch/api/v1/infrastructure/clouds/amazon-us-east-n-virginia/networks/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/cloudlaunch/api/v1/infrastructure/clouds/amazon-us-east-n-virginia/static_ips/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by nuwang** [comment]
@hackdna We think we know why the problem occurs. Can you try saving your credentials for now? That should probably fix the problem. After launching, delete the credentials. We'll put in a longer term fix soon.

**Comment by nuwang** [comment]
You may need to set your saved credentials as the default for that cloud.

**Comment by hackdna** [comment]
Thanks for providing a workaround. I can wait for the fix.
