### ISSUE TITLE
Cannot start a previously existing Galaxy CloudMan instance

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudlaunch#119]
After fetching saved clusters, CloudLaunch reports `'str' object has not attribute 'get'`, which originates from processing app config in CloudMan app plugin (https://github.com/galaxyproject/cloudlaunch/blob/dev/django-cloudlaunch/cloudlaunch/backend_plugins/cloudman_app.py#L31). It seems the data structure for the `cloudman_config` is off showhow as instead of containing much of `persistent_data`, it's just the name of the save cluster bucket:
![image](https://user-images.githubusercontent.com/338642/33288235-8f4867e8-d389-11e7-89c6-79526fa94a5d.png)

**Comment by nuwang** [comment]
Fixed in: https://github.com/galaxyproject/cloudlaunch-ui/commit/04faca6bb038724d53bb177a2f0d59810fe28290

**Comment by nuwang** [comment]
Also, webui has been redeployed to server.
