### ISSUE TITLE
CloudLaunch v0.2 permanently loading

### ISSUE THREAD

**Issue by HEHgit** [galaxyproject/cloudlaunch#120]
Hi, 
I'm using CloudLaunch for galaxy cloudman. 
CloudLaunch was working until yesterday, but today the website is permanently loading without opening.
I'm using Chrome but I also tried with Explorer, Firefox and in the incognito mode, and I got the same issue all the time.

Thank you in advance for your help.

**Comment by nuwang** [comment]
@HEHgit Thanks for reporting this - it looks like an upstream dependency was broken. It's been fixed in this commit: https://github.com/galaxyproject/cloudlaunch-ui/commit/c82fb67a1ce0b7d28111526ff5cd6671fa2a5108
The change has been redeployed and it should be working now.
