### ISSUE TITLE
No such user or invalid password

### ISSUE THREAD

**Issue by HEHgit** [galaxyproject/cloudlaunch#121]
Hi,

I'm using CloudLaunch for galaxy cloudman, and in the "Cluster info log" I can read the messages:

"PROBLEM, running command 'sudo -u hdfs hadoop fs -mkdir /user/cloudgene' returned code '1', the following stderr: 'sudo: unknown user: hdfs sudo: unable to initialize policy plugin ' and stdout: ''

and

PROBLEM, running command '/bin/su - galaxy -c "export GALAXY_RUN_ALL='TRUE'; export GALAXY_HOME='/mnt/galaxy/galaxy-app'; export TMPDIR='/mnt/galaxy/tmp'; export TEMP='/mnt/galaxy/tmp'; source $GALAXY_HOME/.venv/bin/activate; sh $GALAXY_HOME/run.sh --stop-daemon"' returned code '1', the following stderr: '' and stdout: 'Activating virtualenv at .venv Requirement already satisfied: pip>=8.1 in ./.venv/lib/python2.7/site-packages Activating virtualenv at .venv Handling main with log file main.log... PID in main.pid is not valid (deleting) Handling web1 with log file web1.log... Handling web2 with log file web2.log... PID in web2.pid is not valid (deleting) Handling handler0 with log file handler0.log... Handling handler1 with log file handler1.log... PID in handler1.pid is not valid (deleting) Handling handler2 with log file handler2.log... Handling manager0 with log file manager0.log... PID in manager0.pid is not valid (deleting) '

I can access to Galaxy anyway, but I can't login in Galaxy with my credentials and I can't reset the password (Mail is not configured for this Galaxy instance and password reset information cannot be sent. Please contact your local Galaxy administrator). 

Thanks in advance for your help

**Comment by afgane** [comment]
The first issue is not a concern unless you're trying to use Cloudgene service.

For the second issue - is that the current state or was that reported in the log while in the end it recovered? The message seems to indicate Galaxy didn't start but if you can access it, it sounds like it recovered.
And for the password - yes, the mail server is not easy to setup for these transient instances so unless you can remember your password, it may be necessary to create another user. If you need data from the original username, you can become an admin with the second user and impersonate the first user (https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L1054).

(btw, our old launcher had to be restarted last night and afterwards it processed stale requests for launching instances. You may want to check your AWS console to see if there are unwanted instances running and shut them down)

**Comment by afgane** [comment]
@HEHgit please reopen this issue if you're experience this issue again. For now, I'll just close it until we get more details on it.
