### ISSUE TITLE
Support getting an auth token when logging in through OpenID Connect

### ISSUE THREAD

**Issue by machristie** [galaxyproject/cloudlaunch#125]
There [are several ways of generating a Django REST Framework auth token](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) but they all either require a username and password or by using the admin or manage.py commands. There isn't, as far as I can tell, a self-service way for a user authenticating with OpenID Connect to get an auth token.

Implementing such a view should be seems pretty simple though. Essentially we need a view that requires SessionAuthentication and [generates and returns a token](https://github.com/encode/django-rest-framework/blob/161dc2df2ccecc5307cdbc05ef6159afd614189e/rest_framework/authtoken/views.py#L20-L21).

The motivation for having such a view is to allow OpenID Connect users of CloudLaunch to be able to authenticate from the cloudlaunch-cli.

**Comment by afgane** [comment]
If I'm following along, I think this would also pave a path for authenticating with cloud providers without us needing to store or acquire credentials directly from the user but could instead request temporary creds from a cloud provider (e.g., AWS) based on the identity token from an authentication provider (e.g., Google).

**Comment by machristie** [comment]
@afgane this is not nearly so ambitious as that 😄 

Let me try to explain it this way. If a user goes to https://beta.launch.usegalaxy.org/today and logs in through GitHub, how would that user obtain a DRF auth token? The user doesn't have a password so the user can't go to https://beta.launch.usegalaxy.org/cloudlaunch/api/v1/auth/login/ to login and get an auth token. That's why I think, in this situation, we need a custom view that would generate an auth token for a user if the user is already logged in (SessionAuthentication).

**Comment by afgane** [comment]
This clarified the workflow/idea. Yes - sounds like we'll need that.
