### ISSUE TITLE
Rename process_app_config to validate_app_config

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/cloudlaunch#139]
As per discussion - validate is probably a more appropriate name. Return value is a "validated config"

**Comment by afgane** [comment]
This whole concept of `app_config` feels a bit unclear. We call it `app_config`, yet the validation method focuses just on user data that is to be passed to an instance (for example: https://github.com/galaxyproject/cloudlaunch/blob/dev/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py#L32) and then the variable that houses the return value is in fact called `final_ud_config`.

In the mean time, we supply the `app_config`, which contains the entire app version config, including the everything that's in that model field, plus anything that the user might have supplied, to the `deploy` method in addition to the _validated_ app config (i.e., `final_ud_config`). 

The docs on these validate/merge methods are minimal and the data flow is really not clear here.

**Comment by nuwang** [comment]
Fixed in: https://github.com/galaxyproject/cloudlaunch/commit/1ef5b89fbd160a80195dab2a7ac32e8ee72d3728#diff-626b539de7052317f2cf428920ec93a3
