### ISSUE TITLE
Eliminate duplication in django's INSTALLED_APPS section

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/cloudlaunch#143]
For CloudMan to work correctly, all of the dependencies for CloudLaunch need to be listed in the INSTALLED_APPS section. See commit here: https://github.com/galaxyproject/cloudman/commit/295d7324fb700713de7dcff04e7484057bddeeb6
Ideally, we'd just list cloudlaunch as the dependency in the INSTALLED_APPS section, and all of cloudlaunch's dependencies would get pulled in automatically.

We need to find a way to reduce or eliminate this duplication.

**Comment by machristie** [comment]
Some research:

1. Check that dependencies are installed with [system check framework](https://docs.djangoproject.com/en/1.8/topics/checks/)
2. Document the required dependencies. For example, [AllAuth just documents what is required](http://django-allauth.readthedocs.io/en/latest/installation.html)
    * likewise [for django-cms](http://docs.django-cms.org/en/latest/how_to/install.html#minimally-required-applications-and-settings)
    * [wagtail](http://docs.wagtail.io/en/v2.0.1/getting_started/integrating_into_django.html#settings)
    * [django-jet](https://github.com/geex-arts/django-jet#installation) and [the dashboard](https://github.com/geex-arts/django-jet#dashboard-installation)
    * [zinnia](http://docs.django-blog-zinnia.com/en/develop/getting-started/install.html#applications)

I looked through several popular django packages on GitHub and when they have multiple installed app dependencies they just document them in the installation notes. There doesn't seem to be a solution here that automatically takes care of dependent apps.

**Comment by machristie** [comment]
@nuwang I think you came up with a solution for this that involves importing cloudlaunch's settings in cloudman. Is that correct? Is there anything more to do with this issue?

**Comment by nuwang** [comment]
@machristie Yes, I think this is ok. I'll push in a fix with the relevant settings.

**Comment by nuwang** [comment]
Fixed in: https://github.com/galaxyproject/cloudman/commit/d0630ef888d94c54c4e18f43fa1206cebf9f1899#diff-2cec1b1885bdcd2329b82165edb85dbe
