### ISSUE TITLE
Galaxy cloudman launch failure

### ISSUE THREAD

**Issue by luoyistonefish** [galaxyproject/cloudlaunch#150]
Message:
FAILURE 
Create appliance task failed: An error occurred (PendingVerification) when calling the RunInstances operation: Your account is currently being verified. Verification normally takes less than 2 hours. Until your account is verified, you may not be able to launch additional instances or create additional volumes. If you are still receiving this message after more than 2 hours, please let us know by writing to aws-verification@amazon.com. We appreciate your patience.

**Comment by afgane** [comment]
Has it been more than 2hrs since your account on AWS was created? If so, can you access their dashboard to verify the credentials you're using?

**Comment by luoyistonefish** [comment]
I just re-launched a new one. Seems working now.
