### ISSUE TITLE
AssociateAddress operation fails when bringing up a 17.05 Galaxy Cloudman cluster

### ISSUE THREAD

**Issue by scottx611x** [galaxyproject/cloudlaunch#163]
### Steps to reproduce
1.  Go to https://launch.usegalaxy.org
2. Select a `Galaxy CloudMan` instance from the catalog
3. Launch a 17.05 cluster on AWS like so:
- ![screen shot 2018-10-30 at 2 21 47 pm](https://user-images.githubusercontent.com/5629547/47741192-0d187080-dc50-11e8-8eb9-4b37d7a0d930.png)
- ![screen shot 2018-10-30 at 2 22 45 pm](https://user-images.githubusercontent.com/5629547/47741193-0d187080-dc50-11e8-9af4-c0fc9626e1a5.png)

### Observed behavior
- Error is shown in appliances listing:
  - ```
     FAILURE 
     Create appliance task failed: An error occurred (AuthFailure) when calling the AssociateAddress 
     operation: You do not have permission to access the specified resource.
     ```
  - ![screen shot 2018-10-30 at 2 23 37 pm](https://user-images.githubusercontent.com/5629547/47741194-0d187080-dc50-11e8-862b-bddda402b8c8.png)
- EC2 is created without a public IP:
  - ![screen shot 2018-10-30 at 2 35 58 pm](https://user-images.githubusercontent.com/5629547/47741666-3ab1e980-dc51-11e8-85e1-3ad35c2e4925.png)

### General Notes:
- This error is misleading because my AWS IAM user has administrative access
- Manually associating an Elastic IP allows for the proper access to the machine which seems to have been provisioned properly aside from this one issue
- I was last able to bring up a cluster without error in this same manner around Sept. 18, 2018


If you need any more information on my end please let me know! Thanks for your help in advance!

**Comment by nuwang** [comment]
@scottx611x Thanks for the detailed error report. I tried launching an instance with the same settings and didn't run into this issue. I also checked the server logs and found the full stack trace:
```
[2018-10-30 14:23:23,497: ERROR/ForkPoolWorker-1314] Task cloudlaunch.tasks.create_appliance[5ab00412-d125-467c-b7e2-a93dd0472d83] raised unexpected: Exception('Create appliance task failed: An error occurred (AuthFailure) when calling the AssociateAddress operation: You do not have permission to access the specified resource.',)
Traceback (most recent call last):
  File "/opt/cloudlaunch-server/django-cloudlaunch/cloudlaunch/tasks.py", line 68, in create_appliance
    provider_config)
  File "/opt/cloudlaunch-server/django-cloudlaunch/cloudlaunch/backend_plugins/cloudman_app.py", line 139, in deploy
    name, task, app_config, provider_config, check_http=False)
  File "/opt/cloudlaunch-server/django-cloudlaunch/cloudlaunch/backend_plugins/simple_web_app.py", line 55, in deploy
    name, task, app_config, provider_config)
  File "/opt/cloudlaunch-server/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py", line 279, in deploy
    provider_config)
  File "/opt/cloudlaunch-server/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py", line 364, in _provision_host
    provider, inst, subnet.network_id if subnet else None)
  File "/opt/cloudlaunch-server/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py", line 103, in _attach_public_ip
    inst.add_floating_ip(fip)
  File "/opt/cloudlaunch-server/.venv/lib/python3.6/site-packages/cloudbridge/cloud/providers/aws/resources.py", line 347, in add_floating_ip
    self._provider.ec2_conn.meta.client.associate_address(**params)
  File "/opt/cloudlaunch-server/.venv/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/cloudlaunch-server/.venv/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the AssociateAddress operation: You do not have permission to access the specified resource.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/cloudlaunch-server/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/cloudlaunch-server/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/cloudlaunch-server/django-cloudlaunch/cloudlaunch/tasks.py", line 80, in create_appliance
    raise Exception(msg) from exc
Exception: Create appliance task failed: An error occurred (AuthFailure) when calling the AssociateAddress operation: You do not have permission to access the specified resource.
```

So nothing really pops out, other than the fact that boto's AssociateAddress call is failing. Could you please try the following:
1. Double check that the AssociateAddress permission has not been accidentally removed under IAM policies and that full permissions are available to the user.
2. Release/delete all existing elastic IPs through the AWS console, and see whether that solves the issue. (the logic tries to reuse existing elastic ips, so something could have gone wrong there)
3. If it still fails, check whether a new elastic IP has been created (it should have been), and whether it can be manually associated.

**Comment by scottx611x** [comment]
Hi @nuwang, thanks for getting back to me so quickly!

My IAM user is assigned a policy with full administrative access:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

I unfortunately am not able to delete/release all of my Elastic IPs currently as some are related to production deployments, but I've gone ahead and cleaned up what I could.

After doing this I'm still running into the same issue. There was also no new Elastic IP created.

I'm still able to manually create and associate a new Elastic IP with the EC2 that has been spun up  and gain access to the properly provisioned CM instance.

**Comment by nuwang** [comment]
@scottx611x Thanks for eliminating those as potential issues. The only other thing I can think of is that there are multiple internet gateways, and perhaps the wrong gateway is being found.
https://github.com/CloudVE/cloudbridge/blob/f277e60ec67ddfaaebab8c26a0edc32f4d666ce9/cloudbridge/cloud/providers/aws/resources.py#L1252

Could you check whether there's more than one internet gateway with the name 'cloudbridge-inetgateway' which happen to be attached to the same VPC?

**Comment by scottx611x** [comment]
@nuwang There exists a VPC: `cloudbridge-net`, with a single Internet Gateway: `cloudbridge-inetgateway` attached to it, no others.

**Comment by nuwang** [comment]
Thanks Scott. The line that's raising the exception (103) is trying to reattach an existing IP. The line in question is here:
behttps://github.com/galaxyproject/cloudlaunch/blob/f27291287f390dffc68980a4cd887ffaa72c4e25/django-cloudlaunch/cloudlaunch/backend_plugins/base_vm_app.py#L103

So presumably, it is either misidentifying an already attached IP as being free, or picking up an unrelated free elastic IP. Would you be able to see whether anything obvious pops out to you?

@afgane @almahmoud Any ideas?

**Comment by almahmoud** [comment]
I tried to launch a Cloudman instance myself, and it worked as expected.
I've been looking at this for a few hours. Following the Sentry issue I was able to pinpoint some potential leads, and I contacted Scott to check on the IP and Instance (by ID procured from Sentry), and in fact the problem is that the IP that is being attached is already in use. I don't yet know why that would happen, but that's my best lead so far!

**Comment by almahmoud** [comment]
https://github.com/CloudVE/cloudbridge/commit/66fd4ad3346b1136717577cae85b35bdac6e614f should solve this issue!
Thanks to a conversation with Scott on Gitter, we found out that the IP Address was not associated with any instance, but was still associated with a Network Interface. Our CloudBridge method was looking for associated instances to check whether an IP is in use, thus not catching the edge case where IPs were not actually released but do not have any associated instances. This commit changes the method to use the "Association ID" instead of "Instance ID", which will be set whenever there is any active Association, thus preventing this from happening.

**Comment by scottx611x** [comment]
@almahmoud Awesome & super speedy! Keep me updated as to when CloudVE/cloudbridge@66fd4ad   is utilized at https://launch.usegalaxy.org and I'll give it another spin. Thanks again @nuwang & @almahmoud

**Comment by afgane** [comment]
I just updated the launch server to include this change so feel free to try it @scottx611x and please let us know how it goes.

**Comment by nuwang** [comment]
Awesome work @almahmoud. Surprised that this flew under the radar for so long. Is there a way we could write a test for this and/or trigger it in a cross-cloud way?

**Comment by scottx611x** [comment]
I'm back up and running again!: ![screen shot 2018-11-01 at 9 02 04 am](https://user-images.githubusercontent.com/5629547/47853342-d4de7280-ddb4-11e8-9f1e-d47a83387dc6.png)

Thanks for the efforts on all fronts and I hope all is well. Going to close this one.
