### ISSUE TITLE
Report to the user when an instance was created but launch failed

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudlaunch#166]
I just experienced a seemingly random failure during an instance launch where CloudLaunch was not able to attach a public IP to an instance, resulting in a failed deployment. However, an instance was launched but the error message that's propagated to the user does no highlight that. In turn, a user may have a running instance without knowing it. We should keep track of the fact an instance was actually launched and if an error occurs late in the deployment stage, include the fact an instance now exists. 
An additional problem in this scenario is that CloudLaunch loses reference to the launched instance and hence deleting it via CloudLaunch is not possible.

**Comment by afgane** [comment]
The second part of this issue is detailed in https://github.com/galaxyproject/cloudlaunch/issues/117

**Comment by nuwang** [comment]
This has been fixed now since a failed launch results in immediate deletion of the instance.
