### ISSUE TITLE
Delete task failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

### ISSUE THREAD

**Issue by xguse** [galaxyproject/cloudlaunch#171]
I have gotten this error twice now when attempting to trash an appliance and start over.

```
UNABLE TO CHECK STATUS 
Delete task failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>
```

**Comment by nuwang** [comment]
@xguse Can you check whether you saved your credentials in cloudlaunch or used temporary credentials? If you used temporary credentials, the instance will have to be deleted through the cloud provider manually - you can only archive the entry from within cloudlaunch. The error message should be a bit more informative than this, so I'll flag this as an enhancement for now.
