### ISSUE TITLE
CloudBridgeBaseException

### ISSUE THREAD

**Issue by jgoldst7** [galaxyproject/cloudlaunch#172]
I was recently trying to launch an instance of genomics virtual lab through cloudlaunch v0.2 on AWS. I got this error 

"FAILURE 
Create appliance task failed: CloudBridgeBaseException: An error occurred (PendingVerification) when calling the RunInstances operation: Your request for accessing resources in this region is being validated, and you will not be able to launch additional resources in this region until the validation is complete. We will notify you by email once your request has been validated. While normally resolved within minutes, please allow up to 4 hours for this process to complete. If the issue still persists, please let us know by writing to aws-verification@amazon.com for further assistance. from exception type: <class 'botocore.exceptions.ClientError'>"

I launched **GVL 4.4.0 (Galaxy 18.05)** on **cloud: Amazon Web Services, region: us-east-1, zone: default**, using credentials that worked, an **m5.xlarge** vm and adding 100 gb of persistant storage. I have successfully done this before. With the only difference now is that I am using an AWS account that is part of an organization instead of the root user AWS account. Could that be causing the error? thanks

**Comment by afgane** [comment]
Yes, it looks like the IAM account you have transitioned to does not have the necessary permissions. I know assigning `AmazonEC2FullAccess` and `AmazonS3FullAccess` policies to the IAM user account works, but if you need more granularity than that, we can poke deeper to try and deduce finer control.

**Comment by jgoldst7** [comment]
Hello, Yes I made sure to attach both of those policies to the IAM user account and then used those credentials in my configuration. Could there be any other reason that error would pop up? Let me know if you need any further information

**Comment by jgoldst7** [comment]
quick follow up, I received an email from AWS saying my account has been verified and now when I rerun it it works, so it looks like it wasn't really an error, just a hold-off until verification. So all is good now, thank you

**Comment by afgane** [comment]
Glad to hear it got sorted out.
