### ISSUE TITLE
galaxy cloud launch failure

### ISSUE THREAD

**Issue by srtandon** [galaxyproject/cloudlaunch#174]
FAILURE Create appliance task failed: CloudBridgeBaseException: An error occurred (InvalidGroup.NotFound) when calling the CreateTags operation: The security group 'sg-03f14413d08de5f1d' does not exist from exception type: <class 'botocore.exceptions.ClientError'> Report this failure?
--

**Comment by afgane** [comment]
Can you try another launch of the same application?

If that does not work, can you log into the AWS console (https://console.aws.amazon.com/ec2/home) and under _Security Groups_ check if security group with `sg-03f14413d08de5f1d` exists. Unless you are using it for something else, try deleting it and repeat the launch procedure. Hopefully this was just a transient timeout issue.
