### ISSUE TITLE
Galaxy Cloudman 2

### ISSUE THREAD

**Issue by srtandon** [galaxyproject/cloudlaunch#175]
FAILURE 
Create appliance task failed: An error occurred (AccessDenied) when calling the CreateRole operation: User: arn:aws:iam::371917449555:user/learn_galaxy is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::371917449555:role/cloudman2-kube-role

help?

**Comment by afgane** [comment]
It seems the AWS account you are using does not have sufficient privileges to create the necessary resources. The `IAM:createRole` needs to be added as an allowed permission on the account.
