### ISSUE TITLE
Unable to check status: botocore.exceptions.NoCredentialsError

### ISSUE THREAD

**Issue by yl3** [galaxyproject/cloudlaunch#181]
Hi,

I am getting the following error on my CloudLaunch instances page:

> UNABLE TO CHECK STATUS
> Health check failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

Weirdly, status checking appears to be successful for about 30 minutes for a newly launched instance until it fails with this error message.

**Comment by nuwang** [comment]
@yl3 Can you confirm whether you used temporary credentials or stored credentials? Temporary credentials are designed to work this way - since they are not stored on the server, once they expire from the client (typically if you reload the page) - it's no longer possible to perform a health check.

**Comment by yl3** [comment]
I was using temporary credentials, so this makes sense. Thank you.

**Comment by yl3** [comment]
As a related question, is there a way to remove such GVL entries from CloudLaunch? When I use Delete Permanently And Archive, the previous launches with temporary credentials just stay there.

**Comment by afgane** [comment]
You can click on the 'Archive' option and that will remove the items from your view. (They will still be available from the 'My Appliances' menu in the masthead under 'Launch History'.)
