### ISSUE TITLE
Can't create AWS appliance for genomic virtual lab

### ISSUE THREAD

**Issue by mainulhossain** [galaxyproject/cloudlaunch#192]
I'm getting following error while trying to create a new appliance in AWS. It seems I need to add GetRole to may user in AWS console. But I am a newbie to AWS and can't do that. Can anyone please help me?

`FAILURE
Create appliance task failed: An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:iam::032942674603:user/<user> is not authorized to perform: iam:GetRole on resource: role genomics-virtual-lab-20-03-11t18-29-cm2-kube-role`

**Comment by gpeet** [comment]
Hit the same issue because of outdated Galaxy instructions. All you need to do is add AdministratorAccess to your AWS IAM profile.

**Comment by mainulhossain** [comment]
Hey, thanks. It works.
