### ISSUE TITLE
For some reason the cloud instance we have is not showing ready from the GVL dashboard

### ISSUE THREAD

**Issue by AechLyons** [galaxyproject/cloudlaunch#193]
This instance has been up and working with no issue for months.  Today one of the data scientists try to get on to it and they are now getting the galaxy site with a red X.

I logged into the pod and restarted the service (run.sh with --daemon flag) and it still shows a red x but no errors when running the run script. I'm not familiar enough with this so my troubleshooting skills are a bit limited.  Anyone else have this issue or can tell me some things to check?

`root@9cb90036f871:/galaxy-central# ./run.sh --daemon
Activating virtualenv at /galaxy_venv
The directory '/home/galaxy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/galaxy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pip>=8.1 in /galaxy_venv/lib/python2.7/site-packages
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/galaxy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/galaxy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: bx-python==0.7.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: MarkupSafe==0.23 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: PyYAML==3.11 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: SQLAlchemy==1.0.15 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: mercurial==3.7.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: numpy==1.9.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: pycrypto==2.6.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: uWSGI==2.0.15 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: bz2file==0.98 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied: ipaddress==1.0.18 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: Paste==2.0.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: PasteDeploy==1.5.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied: docutils==0.14 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied: wchartype==0.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied: repoze.lru==0.6 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied: Routes==2.4.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied: WebOb==1.4.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied: WebHelpers==1.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied: Mako==1.0.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied: pytz==2015.4 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied: Babel==2.4.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 28))
Requirement already satisfied: Beaker==1.7.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 29))
Requirement already satisfied: dictobj==0.3.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied: nose==1.3.7 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 31))
Requirement already satisfied: Parsley==1.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 32))
Requirement already satisfied: six==1.10.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 33))
Requirement already satisfied: Whoosh==2.7.4 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 34))
Requirement already satisfied: galaxy_sequence_utils==1.0.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 35))
Requirement already satisfied: h5py==2.7.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 36))
Requirement already satisfied: pykwalify==1.5.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 39))
Requirement already satisfied: python-dateutil==2.5.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 40))
Requirement already satisfied: docopt==0.6.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 41))
Requirement already satisfied: Cheetah==2.4.4 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 44))
Requirement already satisfied: Markdown==2.6.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 45))
Requirement already satisfied: bioblend==0.7.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 48))
Requirement already satisfied: boto==2.38.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 49))
Requirement already satisfied: requests==2.10.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 50))
Requirement already satisfied: requests-toolbelt==0.4.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 51))
Requirement already satisfied: kombu==3.0.30 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 54))
Requirement already satisfied: amqp==1.4.8 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 55))
Requirement already satisfied: anyjson==0.3.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 56))
Requirement already satisfied: psutil==4.1.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 59))
Requirement already satisfied: pulsar-galaxy-lib==0.8.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 60))
Requirement already satisfied: sqlalchemy-migrate==0.10.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 63))
Requirement already satisfied: decorator==4.0.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 64))
Requirement already satisfied: Tempita==0.5.3dev in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 65))
Requirement already satisfied: sqlparse==0.1.16 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 66))
Requirement already satisfied: pbr==1.8.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 67))
Requirement already satisfied: svgwrite==1.1.6 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 70))
Requirement already satisfied: pyparsing==2.1.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 71))
Requirement already satisfied: Fabric==1.13.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 74))
Requirement already satisfied: paramiko==2.2.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 75))
Requirement already satisfied: ecdsa==0.13 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 76))
Requirement already satisfied: pysam==0.8.4+gx5 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 79))
Requirement already satisfied: python-genomespaceclient==0.1.8 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 82))
Requirement already satisfied: PasteScript in /galaxy_venv/lib/python2.7/site-packages (from pulsar-galaxy-lib==0.8.0->-r requirements.txt (line 60))
Requirement already satisfied: pynacl>=1.0.1 in /galaxy_venv/lib/python2.7/site-packages (from paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: pyasn1>=0.1.7 in /galaxy_venv/lib/python2.7/site-packages (from paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: bcrypt>=3.1.3 in /galaxy_venv/lib/python2.7/site-packages (from paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: cryptography>=1.1 in /galaxy_venv/lib/python2.7/site-packages (from paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: boto3 in /galaxy_venv/lib/python2.7/site-packages (from python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: python-swiftclient in /galaxy_venv/lib/python2.7/site-packages (from python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: cffi>=1.4.1 in /galaxy_venv/lib/python2.7/site-packages (from pynacl>=1.0.1->paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: enum34; python_version < "3" in /galaxy_venv/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: idna>=2.1 in /galaxy_venv/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: asn1crypto>=0.21.0 in /galaxy_venv/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /galaxy_venv/lib/python2.7/site-packages (from boto3->python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /galaxy_venv/lib/python2.7/site-packages (from boto3->python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: botocore<1.10.0,>=1.9.3 in /galaxy_venv/lib/python2.7/site-packages (from boto3->python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: futures>=3.0; python_version == "2.7" or python_version == "2.6" in /galaxy_venv/lib/python2.7/site-packages (from python-swiftclient->python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: pycparser in /galaxy_venv/lib/python2.7/site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko==2.2.1->-r requirements.txt (line 75))
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/galaxy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/galaxy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: psycopg2==2.6.1 in /galaxy_venv/lib/python2.7/site-packages (from -r /dev/stdin (line 1))
Requirement already satisfied: drmaa in /galaxy_venv/lib/python2.7/site-packages (from -r /dev/stdin (line 2))
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Activating virtualenv at /galaxy_venv
The directory '/home/galaxy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/galaxy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pip>=8.1 in /galaxy_venv/lib/python2.7/site-packages
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/galaxy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/galaxy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: bx-python==0.7.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: MarkupSafe==0.23 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: PyYAML==3.11 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: SQLAlchemy==1.0.15 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: mercurial==3.7.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: numpy==1.9.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: pycrypto==2.6.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: uWSGI==2.0.15 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: bz2file==0.98 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied: ipaddress==1.0.18 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: Paste==2.0.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: PasteDeploy==1.5.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied: docutils==0.14 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied: wchartype==0.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied: repoze.lru==0.6 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied: Routes==2.4.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied: WebOb==1.4.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied: WebHelpers==1.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied: Mako==1.0.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied: pytz==2015.4 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied: Babel==2.4.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 28))
Requirement already satisfied: Beaker==1.7.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 29))
Requirement already satisfied: dictobj==0.3.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied: nose==1.3.7 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 31))
Requirement already satisfied: Parsley==1.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 32))
Requirement already satisfied: six==1.10.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 33))
Requirement already satisfied: Whoosh==2.7.4 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 34))
Requirement already satisfied: galaxy_sequence_utils==1.0.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 35))
Requirement already satisfied: h5py==2.7.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 36))
Requirement already satisfied: pykwalify==1.5.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 39))
Requirement already satisfied: python-dateutil==2.5.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 40))
Requirement already satisfied: docopt==0.6.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 41))
Requirement already satisfied: Cheetah==2.4.4 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 44))
Requirement already satisfied: Markdown==2.6.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 45))
Requirement already satisfied: bioblend==0.7.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 48))
Requirement already satisfied: boto==2.38.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 49))
Requirement already satisfied: requests==2.10.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 50))
Requirement already satisfied: requests-toolbelt==0.4.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 51))
Requirement already satisfied: kombu==3.0.30 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 54))
Requirement already satisfied: amqp==1.4.8 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 55))
Requirement already satisfied: anyjson==0.3.3 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 56))
Requirement already satisfied: psutil==4.1.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 59))
Requirement already satisfied: pulsar-galaxy-lib==0.8.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 60))
Requirement already satisfied: sqlalchemy-migrate==0.10.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 63))
Requirement already satisfied: decorator==4.0.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 64))
Requirement already satisfied: Tempita==0.5.3dev in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 65))
Requirement already satisfied: sqlparse==0.1.16 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 66))
Requirement already satisfied: pbr==1.8.0 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 67))
Requirement already satisfied: svgwrite==1.1.6 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 70))
Requirement already satisfied: pyparsing==2.1.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 71))
Requirement already satisfied: Fabric==1.13.2 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 74))
Requirement already satisfied: paramiko==2.2.1 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 75))
Requirement already satisfied: ecdsa==0.13 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 76))
Requirement already satisfied: pysam==0.8.4+gx5 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 79))
Requirement already satisfied: python-genomespaceclient==0.1.8 in /galaxy_venv/lib/python2.7/site-packages (from -r requirements.txt (line 82))
Requirement already satisfied: PasteScript in /galaxy_venv/lib/python2.7/site-packages (from pulsar-galaxy-lib==0.8.0->-r requirements.txt (line 60))
Requirement already satisfied: pynacl>=1.0.1 in /galaxy_venv/lib/python2.7/site-packages (from paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: pyasn1>=0.1.7 in /galaxy_venv/lib/python2.7/site-packages (from paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: bcrypt>=3.1.3 in /galaxy_venv/lib/python2.7/site-packages (from paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: cryptography>=1.1 in /galaxy_venv/lib/python2.7/site-packages (from paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: boto3 in /galaxy_venv/lib/python2.7/site-packages (from python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: python-swiftclient in /galaxy_venv/lib/python2.7/site-packages (from python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: cffi>=1.4.1 in /galaxy_venv/lib/python2.7/site-packages (from pynacl>=1.0.1->paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: enum34; python_version < "3" in /galaxy_venv/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: idna>=2.1 in /galaxy_venv/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: asn1crypto>=0.21.0 in /galaxy_venv/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.2.1->-r requirements.txt (line 75))
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /galaxy_venv/lib/python2.7/site-packages (from boto3->python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /galaxy_venv/lib/python2.7/site-packages (from boto3->python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: botocore<1.10.0,>=1.9.3 in /galaxy_venv/lib/python2.7/site-packages (from boto3->python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: futures>=3.0; python_version == "2.7" or python_version == "2.6" in /galaxy_venv/lib/python2.7/site-packages (from python-swiftclient->python-genomespaceclient==0.1.8->-r requirements.txt (line 82))
Requirement already satisfied: pycparser in /galaxy_venv/lib/python2.7/site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko==2.2.1->-r requirements.txt (line 75))
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/galaxy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/galaxy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: psycopg2==2.6.1 in /galaxy_venv/lib/python2.7/site-packages (from -r /dev/stdin (line 1))
Requirement already satisfied: drmaa in /galaxy_venv/lib/python2.7/site-packages (from -r /dev/stdin (line 2))
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Activating virtualenv at /galaxy_venv
galaxy.tools.deps DEBUG 2020-03-17 16:48:30,221 Unable to find config file './dependency_resolvers_conf.xml'
Entering daemon mode`

Help?

**Comment by nuwang** [comment]
@AechLyons Can you let us know which version of the GVL you are using? Also, which cloud?

**Comment by AechLyons** [comment]
GVL Image: 4.4.0
I deployed in AWS

**Comment by nuwang** [comment]
Normally, the Galaxy logs or cloudman logs would have some details on what might have gone wrong to cause the red X, however, I can't recall any generic reasons for why this might have happened off the top of my head, since our efforts are focussed on GVL 5, and we haven't been working on GVL 4.4 for a while now.

A machine reboot often works wonders in a situation like this, so assuming that this is a stock GVL instance with no manual config changes etc, it often works, but before doing that, there may be something you need to fix.

I noticed that when you attempted the daemon restart, you tried that as the root user. However, Galaxy actions must be run as the `galaxy` user, by using `su galaxy` before running `run.sh --daemon`. Trying to restart the daemon as root may have caused some files to be recreated with root ownership and therefore, if you perform a reboot, the incorrect file ownership could trip things up.

Therefore, the first thing to try right now is to make sure that everything under /mnt/galaxy/galaxy-app is in fact owned by the galaxy user: `chown -R galaxy:galaxy /mnt/galaxy/galaxy-app`.

Once done, try a reboot, and check whether the situation resolves itself. If not, please post the cloudman logs (/var/log/cloudman) and we can hopefully spot whether something is amiss.

**Comment by AechLyons** [comment]
Ok I'll try that.  Thanks.  Is there a way to upgrade/update to GVL 5 or does that require a complete redeployment via the online tool?

**Comment by nuwang** [comment]
Hmm... looks at this again, I'm a bit confused. Are you sure you're running a GVL 4.4? The galaxy-central folder is used by https://github.com/bgruening/docker-galaxy-stable, not the GVL. Wrong repo perhaps?

**Comment by nuwang** [comment]
Yes, there's no easy upgrade path to GVL 5 unfortunately. It's a ground up rewrite. A fresh launch is needed.

**Comment by AechLyons** [comment]
I grabbed the ver from the GVL dashboard under about.....was that not the right place to verify?

**Comment by nuwang** [comment]
That is the right place, but you mentioned logging into a docker container. I also see a mention of a galaxy-central folder. Unless my memory is faulty, the GVL is using galaxy-app. Have you perhaps replaced the default galaxy version with the docker version perhaps?

**Comment by AechLyons** [comment]
Its quit possible that happened.  This is something I dont normally mess with often.  Its usually a firedrill.  I do remember creating a ASAIM extension at the data scientists requests.  I might be on my own with this one.  Dammit
