### ISSUE TITLE
Log in to Keycloak email address and password

### ISSUE THREAD

**Issue by CynStr** [galaxyproject/cloudlaunch#204]
I am able to successfully run GVL 5.0 beta3, however, what email and password combo am I to enter in the GVL launch window that appears after clicking the "Access address" link? I logged into CloudLaunch using Github but then then Github login does not work on the "Log in to Keycloak" window. The instructions in the Galaxy site are outdated and refer to a login ID and password (not an email address.

**Comment by nuwang** [comment]
Hi @CynStr,

The username will be: admin
You have to use the same password you provided at launch time to cloudlaunch.

**Comment by CynStr** [comment]
Thanks!

**Comment by CynStr** [comment]
Me again, I am now able to launch but the galaxy link leads to a page "503 Service Temporarily Unavailable". Any update on when galaxy will be available again through GVL?

**Comment by almahmoud** [comment]
There is a slight delay (roughly 2-3 minutes on AWS in my experience) between when the GVL app dashboard (I.e. CloudMan) and Galaxy come up, during which Galaxy path will respond with 503. This should be resolved automatically if you wait a bit longer. If not, it means the galaxy deployment is failing to come up. What machine size did you use and what cloud are you running on in that case?

**Comment by CynStr** [comment]
Thanks for the response. I'm using AWS. I was just being impatient, it works if I wait.
