### ISSUE TITLE
GVL5.0 beta3 installation failure

### ISSUE THREAD

**Issue by miaeyaho** [galaxyproject/cloudlaunch#205]
Hello,
I want to install GVL5.0 beta3 (galaxy20.01) on my Amazon cloud platform. However, I repetitively failed with the below failure message. Could you please let me know the way to solve this problem? I'm a beginner, so I really appreciate for you to show me the easiest solution as possible (:D). Thank you!
---------------------------------------------------------------------------------------------------------------------------
FAILURE
Create appliance task failed: An error occurred (AccessDenied) when calling the CreatePolicy operation: User: arn:aws:iam::447458769319:user/galaxy_cloudman is not authorized to perform: iam:CreatePolicy on resource: policy cm2-kube-policy
----------------------------------------------------------------------------------------------------------------------------

**Comment by almahmoud** [comment]
You can either give yourself `AdministratorAccess` through the IAM console link given above, (and here's a rough tutorial for it: https://www.sweetprocess.com/procedures/_eG30mkvYDrfAmevj78A0i6E1GZE/add-an-administrator-to-your-amazon-aws-account/ ) or create an IAM policy (
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage.html) mimicking the following specifications would be enough if you don't want to be a full account administrator:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "iam:CreateInstanceProfile",
                "iam:GetRole",
                "iam:PassRole",
                "iam:CreateServiceLinkedRole",
                "iam:GetInstanceProfile",
                "iam:GetPolicy",
                "iam:CreatePolicy",
                "iam:CreateRole",
                "iam:AttachRolePolicy",
                "iam:AddRoleToInstanceProfile"
            ],
            "Resource": [
                "arn:aws:iam::*:instance-profile/*",
                "arn:aws:iam::*:role/*",
                "arn:aws:iam::*:policy/cm2-kube-policy"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "iam:DescribeKeyPairs",
            "Resource": [
                "arn:aws:iam::*:instance-profile/*",
                "arn:aws:iam::*:role/*",
                "arn:aws:iam::*:policy/cm2-kube-policy"
            ]
        }
    ]
}
```
