### ISSUE TITLE
 GVL 5.0 beta4 (Galaxy 20.05) Failure

### ISSUE THREAD

**Issue by elettod** [galaxyproject/cloudlaunch#211]
I cannot start the instance. Please take in account that I am a new user, with no experience. Thank you!

FAILURE
Create appliance task failed: An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:iam::212571630875:user/cloudlaunch is not authorized to perform: iam:GetRole on resource: role elettod-genomics-virtual-lab-20-08-10-cm2-kube-role

**Comment by nuwang** [comment]
@elettod This is because your AWS account does not have sufficient privileges. Please refer to these issues for more info: https://github.com/galaxyproject/cloudlaunch/issues/205
https://github.com/galaxyproject/cloudlaunch/issues/207
