### ISSUE TITLE
 Galaxy CloudMan - Running but failing the Health Test

### ISSUE THREAD

**Issue by elettod** [galaxyproject/cloudlaunch#213]
Hello,
I am still trying to get Galaxy on AWS. This time with CloudMan.

I find it quite peculiar that, right before clicking on the Health Test button, the instance was running ok.

Here is the message I get (it is always the same):
UNABLE TO CHECK STATUS
Health check failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

**Comment by almahmoud** [comment]
See https://github.com/galaxyproject/cloudlaunch/issues/212#issuecomment-672057147 . Also note Galaxy CloudMan is old and to my knowledge no longer maintained. The GVL is the newest released version of CloudMan.
