### ISSUE TITLE
GVL- Secure Connection Failed

### ISSUE THREAD

**Issue by elettod** [galaxyproject/cloudlaunch#214]
First of all, I'd like to thank you for all the precious tips you provided me with.

I feel I am making some progress. Getting there...hopefully.

This time, I'm facing a security issue:
clouldlaunch seems to work properly, but I cannot access the URL. Tried on different network and via firefox, chrome and mozilla.

Here is the error I am getting:
An error occurred during a connection to 52.204.150.250. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Interestingly, for a fraction of a sec I can see this:
![gvl-200812](https://user-images.githubusercontent.com/46454146/89982021-3e233300-dc75-11ea-8ad7-13074d0e4c75.png)

**Comment by nuwang** [comment]
@elettod  This looks like a browser issue perhaps? https://appuals.com/pr-end-of-file-error/
Are you behind a firewall? Can you try a different browser?

**Comment by elettod** [comment]
Thank you @nuwang 
I have tried on different networks and with edge, chrome and mozilla.
No joy so far.

**Comment by nuwang** [comment]
@elettod Do you have an instance running? I tried the ip above but it seems to be no longer available?

**Comment by elettod** [comment]
@nuwang I have started it again. It is up and running.
Thank you again for trying

**Comment by nuwang** [comment]
@elettod It doesn't seem to have come up? https://52.204.150.250/ says connection refused.

**Comment by elettod** [comment]
According to CloudLaunch, it is running.
The same from the AWS console.

**Comment by elettod** [comment]
I dunno if it matters (or makes any sense), but I want to tell you that the
instance runs on T2.micro.
Is it too small?

Would it be very nice to have an updated tutorial as in the attached
youtube video for CloudMan.

In the meantime, I have decided to stop it again.

Thank you anyway

D

**Comment by elettod** [comment]
I dunno if it matters (or makes any sense), but I want to tell you that the instance runs on T2.micro.Is it too small?
Would it be very nice to have an updated tutorial as in the attached youtube video for CloudMan.

In the meantime, I have decided to stop it again.
Thank you anyway
D

**Comment by nuwang** [comment]
It wasn't possible to ping it or even connect via ssh, so the machine doesn't seem to have come up correctly. Try deleting and relaunching. However, t2.micro is definitely too small I'm afraid. The minimum supported size is the one that's selected by default in cloudlaunch (m5.2xlarge). This costs more than $300 a month as I recall.
