### ISSUE TITLE
Issue in launching Galaxy through IGV

### ISSUE THREAD

**Issue by LohitakshKaushik** [galaxyproject/cloudlaunch#216]
![image](https://user-images.githubusercontent.com/70168697/91082639-8fb0c200-e666-11ea-88e3-0efa0e1f54bf.png)
I have this issue whenever i try to launch something, I usef1x2

**Comment by afgane** [comment]
This is an issue with permissions on your AWS account. Please see this issue for how to set the appropriate permissions: https://github.com/galaxyproject/cloudlaunch/issues/205#issuecomment-655128387.

I'll close this issue so please open another one if you encounter other problems.
