### ISSUE TITLE
Create appliance failure

### ISSUE THREAD

**Issue by vinodsuresh** [galaxyproject/cloudlaunch#217]
I have consistently been getting a 'create appliance failure' over the last 48 hours. My Nectar dashboard shows that an instance is running; the cloudlaunch dashboard shows that the deployment is not found. Any suggestions?

<img width="561" alt="Screen Shot 2020-09-02 at 1 03 00 PM" src="https://user-images.githubusercontent.com/3904884/91920287-b03ee300-ed1c-11ea-8eaa-7e9944e2d8f5.png">

**Comment by nuwang** [comment]
@vinodsuresh Most likely, this was a transient issue on NeCTAR. Feel free to reopen if you encounter this again.
