### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by mciccare** [galaxyproject/cloudlaunch#220]
FAILURE
Create appliance task failed: An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:iam::943603690632:user/cloudlaunch is not authorized to perform: iam:GetRole on resource: role mciccare-genomics-virtual-lab-20-09-16t16-08-cm2-kube-role 

The user has EC2 and S3 permissions as directed.  What's missing?

**Comment by nuwang** [comment]
Please refer to this issue for info: https://github.com/galaxyproject/cloudlaunch/issues/198#issuecomment-655128278
