### ISSUE TITLE
Failure in creation of appliance

### ISSUE THREAD

**Issue by mciccare** [galaxyproject/cloudlaunch#221]
UNABLE TO CHECK STATUS Health  check failed: CloudBridgeBaseException: Unable to locate credentials  from exception type: <class  'botocore.exceptions.NoCredentialsError'>  Report this failure? |  
-- | --

**Comment by nuwang** [comment]
I'm guessing you are using temporary credentials? Please refer here: https://github.com/galaxyproject/cloudlaunch/issues/212
