### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by mciccare** [galaxyproject/cloudlaunch#222]
503 Service Temporarily Unavailable
openresty/1.15.8.1

Appliance: Genomics Virtual Lab (GVL) Version: GVL 5.0 beta4 (Galaxy 20.05)
Cloud: Amazon Web Services 

According to Cloud Launch console GVL is up and running.  The access address is given, but pointing to this address gives the above error, after very briefly flashing the application screen.

**Comment by nuwang** [comment]
@mciccare What instance size did you use? If the instance size is less than the minimum recommended, there's a chance that some services won't load. That may explain the behaviour you are seeing?

**Comment by mciccare** [comment]
m5.2xlarge

**Comment by mciccare** [comment]
I have an instance running at 107.20.19.77.  Both Cloudlaunch and AWS indicate all is well.  But https://107.20.19.77/ simply replies "default backend 404".  I cannot ping this address.

**Comment by nuwang** [comment]
@mciccare This may have been due to a machine image issue. Can you please retry?
