### ISSUE TITLE
Failure to create

### ISSUE THREAD

**Issue by mciccare** [galaxyproject/cloudlaunch#223]
FAILURE
Create appliance task failed: An error occurred while running the ansible playbook to configure instance. Check the logs. Last output lines were: ['TASK [docker : Ensure old versions of Docker are not installed.] ***************', 'ok: [54.83.252.154]', '', 'TASK [docker : Ensure dependencies are installed.] *****************************', 'fatal: [54.83.252.154]: FAILED! => {"msg": "Failed to open session: SSH session not active"}', '', 'PLAY RECAP *********************************************************************', '54.83.252.154 : ok=7 changed=3 unreachable=0 failed=1 skipped=1 rescued=0 ignored=1 ', '', '']

**Comment by nuwang** [comment]
@mciccare This should be fixed now. Thanks for reporting.
