### ISSUE TITLE
launch the Galaxy instance on AWS failure with GLV

### ISSUE THREAD

**Issue by cearch123** [galaxyproject/cloudlaunch#224]
FAILURE 
Create appliance task failed: An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:iam::101035347665:user/Galaxy_Cloudman is not authorized to perform: iam:GetRole on resource: role cearch-cloudman-20-20-09-27t07-09-cm2-kube-role

**Comment by almahmoud** [comment]
Please refer to this issue for info: https://github.com/galaxyproject/cloudlaunch/issues/198#issuecomment-655128278
