### ISSUE TITLE
UNABLE TO CHECK STATUS 

### ISSUE THREAD

**Issue by cearch123** [galaxyproject/cloudlaunch#225]
UNABLE TO CHECK STATUS 
Health check failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'

**Comment by almahmoud** [comment]
I'm guessing you are using temporary credentials? Please refer here: https://github.com/galaxyproject/cloudlaunch/issues/212
