### ISSUE TITLE
cloud launch chemical toolbox failure

### ISSUE THREAD

**Issue by brainsnewmath** [galaxyproject/cloudlaunch#227]
UNABLE TO CHECK STATUS 
Health check failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

Even though the ec2 instance is up and can be connected via ssh.

**Comment by nuwang** [comment]
@brainsnewmath Please refer to this issue: https://github.com/galaxyproject/cloudlaunch/issues/212
