### ISSUE TITLE
Could not set up a Galaxy instance of AWS via GVL

### ISSUE THREAD

**Issue by cearch123** [galaxyproject/cloudlaunch#232]
Hello, Ms/Mr.

Could you help me with the AWS instance set-up with your GVL tools, the failure message is as following:

FAILURE
Create appliance task failed: CloudBridgeBaseException: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Invalid availability zone: [ap-northeast-1b] from exception type: <class 'botocore.exceptions.ClientError'>

My e-mail is : nieshuang@nantian.com.cn, 

Great thanks

Shuang NIe

**Comment by nuwang** [comment]
Fixed.
