### ISSUE TITLE
Getting No Credentials Error When Trying to Launch Genomics Virtual Lab

### ISSUE THREAD

**Issue by DSVT-Git** [galaxyproject/cloudlaunch#236]
Getting this error message when I try to launch Genomics Virtual Lab...

UNABLE TO CHECK STATUS
Health check failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

Have tried delete the instance and creating a new instance but it happens again...

**Comment by afgane** [comment]
This occurs when the credentials are not stored on CloudLaunch because it has no way to check on the status of the instance or delete it. A slightly longer explanation can be found here: https://github.com/galaxyproject/cloudlaunch/issues/212#issuecomment-672057147
