### ISSUE TITLE
GVL Galaxy: Error during initial launch

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/cloudlaunch#237]
Appliance: Genomics Virtual Lab (GVL)Version: GVL 5.0 beta4 (Galaxy 20.05)
Cloud: Amazon Web Services

FAILURE
Create appliance task failed: An error occurred while running the ansible playbook to configure instance. Check the logs. Last output lines were: ['changed: [34.194.106.1] => (item=ubuntu)', '', 'TASK [Install system packages] *************************************************', 'changed: [34.194.106.1] => (item=python-backports.ssl-match-hostname)', 'fatal: [34.194.106.1]: FAILED! => {"msg": "Failed to open session: SSH session not active"}', '', 'PLAY RECAP *********************************************************************', '34.194.106.1 : ok=18 changed=11 unreachable=0 failed=1 skipped=4 rescued=0 ignored=1 ', '', '']

**Comment by nuwang** [comment]
@dwightkuo Can you give it another go? This should be fixed now.
