### ISSUE TITLE
Trinity de novo hung cloning

### ISSUE THREAD

**Issue by pfordnc** [galaxyproject/cloudlaunch#241]
I was able to successfully deploy the Genomics appliance into AWS I get connected to it via the public IP address and launch Galaxy from the main page then I go to Admin => Tool Shed => & attempt to load Trinity De Novo it hangs "cloning" for more than 2 hours.  where can I look to try & troubleshoot this issue. many thanks!

**Comment by nuwang** [comment]
@pfordnc When installing tools, make sure not to select the shed_tool_conf.xml as the target, as that's read only. At present, this is still selected by default, but I believe a fix was either already made or is in the works. Also unselect dependencies as follows:


![image](https://user-images.githubusercontent.com/2070605/100878338-0ebc5e80-34d0-11eb-83ed-61019c7c10e9.png)
