### ISSUE TITLE
Galaxy Genomics Virtual Lab setup error "Get Role"

### ISSUE THREAD

**Issue by tshum-create** [galaxyproject/cloudlaunch#245]
I received this error message below when I tried to launch "Appliance: Genomics Virtual Lab (GVL), Version: GVL 5.0 beta5 (Galaxy 20.09)" on Amazon Web Services, using the website https://launch.usegalaxy.org/appliances.

FAILURE
Create appliance task failed: An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:iam::596091794167:user/galaxy_cloudman is not authorized to perform: iam:GetRole on resource: role tshum-genomics-virtual-lab-20-12-24-2020-cm2-kube-role

**Comment by almahmoud** [comment]
This is because your AWS IAM account does not have sufficient privileges. See this issue for more details: https://github.com/galaxyproject/cloudlaunch/issues/198#issuecomment-655128278
