### ISSUE TITLE
Cannot delete a cloud launch

### ISSUE THREAD

**Issue by tshum-create** [galaxyproject/cloudlaunch#246]
Hi, I wanted to delete this active appliance but the website is not letting me do it. Can you please help me with this problem?

thomas3-genomics-virtual-lab-20-12-24t21-23Appliance: Genomics Virtual Lab (GVL)Version: GVL 4.3.0 (Galaxy 17.09)Cloud: Amazon Web Services | 7 hours ago | UNABLE TO CHECK STATUSHealth check failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'> Report this failure? | http://34.202.171.49/ |  
-- | -- | -- | -- | --

Thanks,
Thomas

**Comment by almahmoud** [comment]
You can only delete applications from CloudLaunch if you've saved credentials. See: https://github.com/galaxyproject/cloudlaunch/issues/212#issuecomment-672057147
