### ISSUE TITLE
Unable to select instance - Server Error 500 

### ISSUE THREAD

**Issue by rpetit3** [galaxyproject/cloudlaunch#248]
Hello!

When trying to select an instance type, I'm getting a 500 error code. I am unable to select an instance to launch Galaxy.

 I've attached a screenshot.

![cloudlaunch](https://user-images.githubusercontent.com/5334269/106474780-3e0d2e80-6473-11eb-9808-7e3c2e39d793.PNG)
![cloudlaunch2](https://user-images.githubusercontent.com/5334269/106474855-53825880-6473-11eb-8bd6-a70dd9932b06.PNG)

Here's console log in Chrome incase something sticks out
![console](https://user-images.githubusercontent.com/5334269/106475789-57fb4100-6474-11eb-868d-f0df605973a9.PNG)

Please let me know if there's any info I can provide to help out

**Comment by nuwang** [comment]
@rpetit3 Has this been resolved? Can you let us know which cloud this is on. Also can you try reentering and revalidating your credentials?

**Comment by rpetit3** [comment]
Hi @nuwang 

After reentering my credentials I am getting the same errors as my previous issue https://github.com/galaxyproject/cloudlaunch/issues/242 again.

```
Error: The credentials you have entered could not be validated.

ERROR Details: Authentication with cloud provider failed: CloudBridgeBaseException: An error occurred (AuthFailure) when calling the DescribeKeyPairs operation: AWS was not able to validate the provided access credentials from exception type: <class 'botocore.exceptions.ClientError'>
```

I've tried entering credentials as `aws` and `aws-us`

**Comment by almahmoud** [comment]
If you can possibly find out like before, is it still hitting `ap-northeast-1`  or is this another issue?

**Comment by nuwang** [comment]
The `ap-northeast-1` issue should be resolvable since @almahmoud  added this cloud option:
![image](https://user-images.githubusercontent.com/2070605/108162354-f2b17c00-7112-11eb-84c7-9c75d1aef2ec.png)

Perhaps your credentials are invalid? Can you check with boto perhaps?

**Comment by nuwang** [comment]
Just in case, can you also try deleting all existing credentials from cloudlaunch, and entering afresh? You can view your credentials in the top right hand corner under your username -> My Credentials.

**Comment by rpetit3** [comment]
I'm following up with IT to see if they are getting the requests.

Haha I would love to try with Boto, but in addition to being region locked the credentials are also IP locked to 149.165.157.211 which I got from `dig launch.usegalaxy.org`

I'll update soon

**Comment by rpetit3** [comment]
Good news, it's us. The credentials I was given were deleted by an automated process.

Going to close this. Thanks for the help.
