### ISSUE TITLE
Spawning GVL 5.0 beta5 fails

### ISSUE THREAD

**Issue by timp0** [galaxyproject/cloudlaunch#249]
Hi,

Getting an error when trying to spawn a galaxy instance (Galaxy 20.09) via GVL: 

```FAILURE
Create appliance task failed: An error occurred (MalformedPolicyDocument) when calling the CreatePolicy operation: Syntax errors in policy.```

Any suggestions?

**Comment by nuwang** [comment]
@timp0 Can you let us know which cloud you tried this on? I just tried on AWS and it launched ok.

**Comment by timp0** [comment]
@nuwang yeah, it was on AWS for me as well.  At first I had some problems until I gave the IAM admin permissions (GetRole, SetRole), but this problem still persists.  Wasn't clear how to get any further logs to share, please let me know what other details I can provide.

**Comment by afgane** [comment]
The docs are outdated on the required permissions (in (small) part what's holding the GVL in beta). This issue has the list of required permissions: https://github.com/galaxyproject/cloudlaunch/issues/198#issuecomment-655128278

**Comment by nuwang** [comment]
@timp0 Also, what name did you give your deployment? It's possible that if the name is too long, it could result in some issues.

**Comment by timp0** [comment]
I tried several names, most recently "jhubmeclasstest" which is pretty short.

I tried adding the specific permissions, didn't seem to help.  Here's a screenshot of the error.  I'll note Galaxy 17 seems to start fine.

![image](https://user-images.githubusercontent.com/1441855/108579729-429c6880-72f6-11eb-9fe7-0601a97b2c70.png)

**Comment by almahmoud** [comment]
I just launched an instance on AWS and it is up and running as expected.
I believe this might be related to your IAM policy on your account. Maybe try to see if this helps: https://stackoverflow.com/questions/24026348/aws-malformed-policy-error

**Comment by nuwang** [comment]
@timp0 Can you give it a go now?
