### ISSUE TITLE
Error creating my own galaxy cluster... 

### ISSUE THREAD

**Issue by Urquizu95** [galaxyproject/cloudlaunch#252]
I have problems creating my galaxy cluster with aws, I put all the credentials and permisions and this error still hapen:

FAILURE
Create appliance task failed: An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:iam::208565580221:user/galaxy-cloudman is not authorized to perform: iam:GetRole on resource: role cesar-genomics-virtual-lab-21-03-10t13-51-cm2-kube-role

Someone know what can I do??

**Comment by afgane** [comment]
Please take a look at this comment and that should address the issue: https://github.com/galaxyproject/cloudlaunch/issues/198#issuecomment-655128278
