### ISSUE TITLE
Log In failed

### ISSUE THREAD

**Issue by notetienne** [galaxyproject/cloudlaunch#253]
Hello,

I'm running my own instance of GVL on AWS, It's running perfectly but I don't know which email to enter in the KeyCloak landing page.

I tried ubuntu, I tried leaving it empty, I tried my GitHub email (I logged in CloudLaunch with my github account but I can't enter any email in my CloudLaunch account)

Thank you for your help

**Comment by almahmoud** [comment]
The username is always `admin` and the password should be the one you set at launch. Let us know if you have other problems.
