### ISSUE TITLE
cloudlaunch newbie, got this error

### ISSUE THREAD

**Issue by stvlar** [galaxyproject/cloudlaunch#254]
FAILURE
Create appliance task failed: An error occurred while running the ansible playbook to configure instance. Check the logs. Last output lines were: ['', 'PLAY [Bootstrap Docker Container] **********************************************', '', 'TASK [Wait for any possibly running unattended upgrade to finish] **************', 'fatal: [35.175.74.15]: UNREACHABLE! => {"changed": false, "msg": "timed out", "unreachable": true}', '', 'PLAY RECAP *********************************************************************', '35.175.74.15 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0 ', '', '']

**Comment by afgane** [comment]
It looks like automatic upgrade process never completed. Have you tried the launch process more than once? If not, I'd suggest deleting this one and starting over. Probably a good idea to log into the cloud console and make sure the virtual machine got deleted there.
