### ISSUE TITLE
Error trying to launch appliance

### ISSUE THREAD

**Issue by seanExcisionBio** [galaxyproject/cloudlaunch#255]
I have received the following error when trying to instantiate a new appliance: 

Create appliance task failed: An error occurred while running the ansible playbook to configure instance. Check the logs. Last output lines were: ['changed: [3.229.1.108] => (item=python-backports.ssl-match-hostname)', 'changed: [3.229.1.108] => (item=python-pip)', '', 'TASK [Install pip modules] *****************************************************', 'fatal: [3.229.1.108]: FAILED! => {"changed": false, "msg": "Unable to find any of pip3 to use. pip needs to be installed."}', '', 'PLAY RECAP *********************************************************************', '3.229.1.108 : ok=21 changed=14 unreachable=0 failed=1 skipped=4 rescued=0 ignored=1 ', '', '']

Any help in remedying the issue would be much appreciated.

**Comment by almahmoud** [comment]
This was due to the old playbook using python2 but we've since fixed it. Please re-open the issue if you hit this again.
