### ISSUE TITLE
Create task failed

### ISSUE THREAD

**Issue by jackbrougher** [galaxyproject/cloudlaunch#256]
Hello,

I'm following the launch guide, but I'm getting this error message below. Any suggestions?

FAILURE
Create appliance task failed: An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:iam::625424302336:user/galaxy_cloudman is not authorized to perform: iam:GetRole on resource: role jackson0-genomics-virtual-lab-21-06-18t23-52-cm2-kube-role

**Comment by almahmoud** [comment]
This seems like a lack of appropriate permissions. Please see this comment for appropriate permissions: https://github.com/galaxyproject/cloudlaunch/issues/198#issuecomment-655128278
and please re-open the issue if that doesn't help.
