### ISSUE TITLE
docs need additional data, re custom AMIs and launch targets

### ISSUE THREAD

**Issue by andersje** [galaxyproject/cloudlaunch#28]
I'm curious as to how I use biocloudcentral to launch my own custom AMIs, and also how I launch those AMIs into a VPC.

Thanks for any help you can lend me.

**Comment by MatthewRalston** [comment]
@afgane would can you confirm that AMI's will launch into a default VPC, however?

**Comment by afgane** [comment]
Yes. If the account only has VPC access, an instance will get launched into the default VPC. I tested this but let me know if you run into issues.

**Comment by MatthewRalston** [comment]
Thank you!

**Comment by MatthewRalston** [comment]
I have another question concerning custom AMIs, [cross posted on biostar](https://biostar.usegalaxy.org/p/14018/). Is your [ansible playbook](https://github.com/galaxyproject/ansible-cloudman-image) the recommended way to build the AMI? Is anything else required? Can I then simply add the image to cloudlaunch?

**Comment by afgane** [comment]
I posted an answer on the biostar forum and depending on how far you'd like to take the cloud functionality, in addition to the AMI, you are likely going to need the the galaxy and indices file systems. The instructions are available at the link I posted (i.e., https://wiki.galaxyproject.org/CloudMan/Building).
