### ISSUE TITLE
Documentation on adding AWS cloud, instance types to fresh install?

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/cloudlaunch#42]
Hi, I'm using the dockerized version from @afgane. I'd like to add the AWS cloud and some instance types, but I don't know where to find informtion about the "EC2 port", "S3" port, or others. Would someone let me know where I can find this information? Thanks for your time!

**Comment by afgane** [comment]
The official EC2 info is available here: http://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region
S3 here: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

You can also look for specific fields within the Cloud Launch repo at the file used to preload the database: https://github.com/galaxyproject/cloudlaunch/blob/master/biocloudcentral/aws_db_data.json

If you're going to use the launcher more permanently, I'd suggest installing it by hand vs. using the current version of the Docker image...
