### ISSUE TITLE
Add EBS optimized setting for master node

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudlaunch#53]
Enabling [EBS optimization](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html) on the master node helps with NFS performance.

**Comment by afgane** [comment]
This may take a while but in the mean time, all volumes are SSD (`gp2` type: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html), so the larger the volume, the better the performance.

**Comment by hackdna** [comment]
I see, thanks. The problem is that the IO bandwidth can be affected by "noisy neighbors" since storage traffic and general network traffic share the same path in non-EBS-optimized instances.

**Comment by hackdna** [comment]
Is bug fixing on hold because of the rewrite (#49)?

**Comment by afgane** [comment]
When I said a while, I was thinking it may not happen today/tomorrow but
I'm looking into it.

**Comment by hackdna** [comment]
OK, thank you! I didn't mean to rush you, just wanted to figure out the state of the project.

**Comment by afgane** [comment]
I managed to squeeze a basic implementation in today - it's live now on launch.usegalaxy.org (with _cloudman-test_ bucket) so feel free to give it a shot and let me know if you'd like to see something different.

**Comment by hackdna** [comment]
Thank you. While the volume IOPS setting is also useful, I actually had the `--ebs-optimized` [instance attribute](http://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-attribute.html) in mind.

**Comment by afgane** [comment]
Is that just a flag to add when launching an instance? And if the instance is already EBS-optimized, nothing changes but if it's not, Amazon charges the extra fee?

**Comment by afgane** [comment]
I guess I should have kept reading... yes: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html#ebs-optimization-support

**Comment by hackdna** [comment]
Yes to both questions. Also, it's worth noting that "EBS-optimized instances enable EC2 instances to fully use the IOPS provisioned on an EBS volume"

**Comment by afgane** [comment]
Should be all good to go now; live on [launch.usegalaxy.org](https://launch.usegalaxy.org). 

I guess the IOPS provisioned volumes came in as a bonus from the original comment... Let me know how performance changes with all this enabled.

**Comment by hackdna** [comment]
Thanks, the IO throughput is a lot more consistent now when writing to `/mnt/galaxy` on master via NFS. Btw, it would be great to enable the `--ebs-optimized` setting on worker nodes too (for example, it is not enabled by default on `c4.large`, contrary to what the docs say).

**Comment by afgane** [comment]
I wasn't sure if that would be beneficial since all the volumes are mounted from the master but I added it in now (available from _cloudman-test_ bucket for the time being).

**Comment by hackdna** [comment]
Great, thanks, working as expected. It is mostly beneficial for speeding up the boot process on worker nodes but also, gp2 is the new default EBS volume type.
