### ISSUE TITLE
Impossible to select a placement zone

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudlaunch#54]
Attempting to fetch the available zone list (after filling out the required fields) results in error message "tuple index out of range".

**Comment by afgane** [comment]
Should be fixed now - a typo lingered around (https://github.com/galaxyproject/bioblend/commit/83ec45c0ee04785004a45dec1a4db55b8277ab7e).

**Comment by hackdna** [comment]
Thanks!
