### ISSUE TITLE
Problem selecting a Cloud and entering an Access key

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudlaunch#55]
Clicking on the Cloud dropdown results in opening of https://github.com/galaxyproject/cloudman/blob/master/CHANGELOG.md in a new window and clicking on the Access key input box results in opening of https://aws-portal.amazon.com/gp/aws/developer/account/index.html?action=access-key in a new window.

**Comment by afgane** [comment]
Thanks for noticing. Forgot to close the href tag on the release notice... fixed now.
