### ISSUE TITLE
List of available clouds

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudlaunch#58]
(this refers to, currently, the `dev` branch)

The following endpoint `http://127.0.0.1:8000/api/v1/infrastructure/clouds/` will list all clouds registered on the instance, even if a user does not have credentials associated with all the available clouds. Should this be so or should the list be filtered based on the creds a user has registered?

**Comment by nuwang** [comment]
This should probably remain so, since a user could provide temporary credentials to browse the clouds. It would be nice to add some UI elements for entering temp. credentials in the browsable API as well.
