### ISSUE TITLE
Support for Neutron Networking?

### ISSUE THREAD

**Issue by amaclean199** [galaxyproject/cloudlaunch#63]
Hello, just wondering if this has been tested with OpenStack's Neutron networking? Specifically on OpenStack Kilo.

**Comment by afgane** [comment]
Is there a particular feature that you have in mind here or did something not work as expected? I don't think the current version has much support for Neutron.
The dev branch (https://github.com/galaxyproject/cloudlaunch/tree/dev) has been tested and appears to work as expected. That branch is under development and not quite ready for use.

**Comment by amaclean199** [comment]
Okay that's what it felt like. I had successfully deployed with Nova networking at the beginning of the year but we have since upgraded our environment. Now I'm trying to redeploy GOTC and running into a number of new issues. We can wait until the development branch is ready for use.

**Comment by katbeaulieu** [comment]
Has anyone made any progress on this? We are looking to deploy Galaxy in the Cloud for an Openstack deployment with Neutron networking and have not found any documentation on this subject.

**Comment by nuwang** [comment]
New rewrite of CloudLaunch works with Neutron. CloudMan is still being upgraded.
