### ISSUE TITLE
Securing Cloudman Galaxy master...

### ISSUE THREAD

**Issue by edwardsnj** [galaxyproject/cloudlaunch#69]
I'm tasked with ensuring that the cloud-based Galaxy instance launched from launch.usegalaxy.org passes the same security scans a permanent server would. I'm using the Cluster with Galaxy option. I've dug around quite a lot, but haven't quite managed to figure out the special magic that would resolve the following issues. I hit most of these issues with the 15.x AMI/Galaxy version I think, but details below were uncovered on the 16.x AMI/Galaxy version.

1. start up in HTTPS mode from the get go (rather than logging into the admin user-interface over HTTP and then toggling ssl mode). 

2. update the Ubuntu instance with the latest security patches. I run "sudo apt-get updates; sudo unattended-upgrades", which seems to be the recommended recipe, and reboot the cluster (via the cloudman/admin link). 

   1. it is unfortunate that there is no hook for a script to run earlier than any Galaxy services run which might save the reboot.

   2. Unfortunately, apache2 is upgraded and configured to start at reboot - its links must be removed from /etc/rc*.d to be consistent with the "before" state of the instance. 

   3. Unfortunately, nginx is upgraded too, and as best I can make out, the upgraded version of ubuntu nginx does not provide the nginx upload module which is used by Galaxy and this makes it fail at startup. The error is "nginx: [emerg] unknown directive "upload_store" in /etc/nginx/..." in /var/log/cloudman/cm_boot.log. 

3. If I stop ProFTPd, this change gets written to the s3 configuration bucket, no problem. However, after the reboot, the Galaxy service is never started by the supervisor, since it is waiting for ProFTPd to be started (and it never is, because it was stopped). 

4. Where/how can I manipulate the ports opened by the security group? What is on the other end of each of these ports - there seems like a lot? I'd like to shut down everything other than HTTPS and SSH (at least to the outside world). 

5. ssh access is permitted with either the password /or/ the key-pair - can I turn off password only access and require the key-pair?

6. (Not strictly a security issue, but observed when rebooting...) a new galaxyIndices volume gets created with each reboot. 

Thanks,

-- n

**Comment by edwardsnj** [comment]
Perhaps this would be better in the galaxyproject/cloudman section...

**Comment by nuwang** [comment]
@edwardsnj Yes, I think it would be better if you could log this under galaxyproject/cloudman. I'll close this for now and wait for you to re-open there.
