### ISSUE TITLE
Add GCE cloud

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudlaunch#78]
Add the ability to interface with the Google Cloud. This will require storing the cloud connection properties in the model and creating appropriate serializers.

Note that support for the Google Cloud in CloudBridge has not been completed but it is sufficient to make progress here. See the _gce_ branch: https://github.com/gvlproject/cloudbridge/tree/gce

**Comment by machristie** [comment]
My notes on the needed changes:

New model needed for GCE cloud
* extend Cloud model
* fields
    * region_name: string
    * zone_name: string

Update domain_models.py:get_cloud_provider to create a GCE CloudProvider

In view_helpers.py
* look for credentials in a single HTTP header that holds the entire credentials
  JSON object
* or look for the credentials in the user profile

New model: GCECredentials
* single field: credentials, which is an encrypted JSON string


I haven't yet looked into the DRF related changes.

**Comment by machristie** [comment]
@afgane I can't assign this issue to myself. Can you assign it to me?

**Comment by afgane** [comment]
@machristie I don't think this is a _assign-yourself_ problem - it looks like a Github limitation: https://github.com/isaacs/github/issues/100

I'll add you as a collaborator to the project.
