### ISSUE TITLE
terminate instances from within CloudLaunch interface

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/cloudlaunch#87]

**Comment by nuwang** [comment]
Enis and Marcus are working on this now. This should happen by the end of the week or next week at the latest.

**Comment by afgane** [comment]
xref https://github.com/galaxyproject/cloudlaunch-ui/issues/18

**Comment by afgane** [comment]
Done for VM-based apps. Still need to implement the delete functionality for CloudMan-based deployments so leaving this open until then.
