### ISSUE TITLE
clear list of instances

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/cloudlaunch#88]
It would be nice to remove entries from the displayed list, especially failed once or instances that are not running anymore.

**Comment by nuwang** [comment]
This is also being worked on by Enis and Marcus. This too should happen in parallel with the other issue.

**Comment by nuwang** [comment]
This was added in: https://github.com/galaxyproject/cloudlaunch-ui/pull/19
but I guess we forgot to update this issue.
