### ISSUE TITLE
Make backend plugins standalone

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/cloudlaunch#89]
This documents a discussion on how we plan to handle backend plugins moving forward:
Currently, backend plugins access some cloudlaunch models, and therefore need a running cloudlaunch instance to be developed, tested or run against. However, there is no real reason to have this dependency, and we should be able to full decouple the two, allowing backend plugins to be executed in a standalone fashion, as well as from within cloudlaunch.

The planned strategy is to send in required objects as dicts. These objects can thus be provided through a commandline runner, say as json docs, as well as CloudLaunch itself. This should make plugin development much easier, and also allow for re-use outside of cloudlaunch.

Further along the line, we will also need to provide a way to bundle a backend plugin, along with its frontend component, and provide it together as a versioned, installable object within CloudLaunch.

**Comment by afgane** [comment]
Started this on a feature branch: https://github.com/galaxyproject/cloudlaunch/tree/decouple-plugins

**Comment by afgane** [comment]
Todo's:
- [ ] Decouple `health status` method
- [ ] Decouple `restart` method
- [ ] Decouple `delete` method
- [ ] Decouple `launch_app` method (structurally and implement for all plugins)
  - [ ] Replace `credentials` with `provider`
  - [ ] Remove dependency on `ApplicationVersionCloudConfig`
  - [ ] Replace dependency on Celery `task` w/ a custom Task class
- Decouple `process_app_config` method (structurally and implement for all plugins)
  - [ ] Replace `credentials` with `provider`
  - [ ] Remove dependency on `ApplicationVersionCloudConfig`
