### ISSUE TITLE
Upgrade Django to 1.11

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudlaunch#93]
Django 1.11 is an LTS, which is what we want to stick with (and 1.9 is no longer supported: https://www.djangoproject.com/download/) so time to upgrade.

**Comment by alenthomas** [comment]
Hi,
I would like to help on this.
I don't see a contribution guide, so it would help if you could let me know how to get started.
I was thinking 
- try to change the django version to 1.11
- run the tests and see where tests fail, and take it on from there

let me know your thoughts

**Comment by bgruening** [comment]
This sounds like a good plan! If you get stuck feel free to create a "work in progress" PR so we can help you.
Thanks for your help!

**Comment by afgane** [comment]
Closed by #97.

**Comment by alenthomas** [comment]
:disappointed:

**Comment by bgruening** [comment]
@alenthomas thats unfortunate. Sorry :(
But there are a few other things you might want to look at. We appreciate any help! Thanks!
