### ISSUE TITLE
Add support for OpenAPI and client bindings for other languages

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/cloudlaunch#95]
With Django Rest Framework Swagger, we should be able to generate an OpenAPI spec for the current API. We can then use that spec to generate client bindings for multiple languages.

- [ ] Generate OpenAPI spec from Django Rest Framework, possibly using DRF Swagger.
References:
a. http://www.django-rest-framework.org/api-guide/schemas/#schemas
b. https://github.com/marcgibbons/django-rest-swagger
- [ ] Generate a python client library using available code generators. Compare and choose a suitable generator:
References:
a. https://github.com/Azure/autorest
b. https://github.com/swagger-api/swagger-codegen
- [ ] Make OpenAPI spec and client library available for download
- [ ] Stretch: Create a commandline client for cloudlaunch

Additional references:
https://apievangelist.com/2015/06/06/comparison-of-automatic-api-code-generation-tools-for-swagger/

**Comment by afgane** [comment]
Heh, I missed this issue when creating #109... so they're duplicates at this point.

**Comment by nuwang** [comment]
Being implemented in: https://github.com/galaxyproject/cloudlaunch/issues/109
